basePath: /
definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  entity.Company:
    properties:
      gln:
        type: integer
      id:
        type: integer
      locations:
        items:
          $ref: '#/definitions/entity.Location'
        type: array
      name:
        type: string
    type: object
  entity.Location:
    description: Simple object
    properties:
      address:
        type: string
      companyRefer:
        type: integer
      houseNr:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Echo Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /companies:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Company'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get Companies
      tags:
      - companies
    post:
      consumes:
      - application/json
      parameters:
      - description: Add company
        in: body
        name: company
        required: true
        schema:
          $ref: '#/definitions/entity.Company'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.Company'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create Company
      tags:
      - companies
  /companies/{companyId}/locations/{locationId}:
    post:
      consumes:
      - '*/*'
      parameters:
      - description: Company ID
        in: path
        name: companyId
        required: true
        type: integer
      - description: Location ID
        in: path
        name: locationId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Company'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Add Location To Company
      tags:
      - companies
  /companies/{id}:
    delete:
      consumes:
      - '*/*'
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete Companies
      tags:
      - companies
    get:
      consumes:
      - '*/*'
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Company'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get Company
      tags:
      - companies
  /locations:
    get:
      consumes:
      - '*/*'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Location'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get Locations
      tags:
      - locations
    post:
      consumes:
      - application/json
      parameters:
      - description: Add location
        in: body
        name: location
        required: true
        schema:
          $ref: '#/definitions/entity.Location'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Location'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get Locations
      tags:
      - locations
  /locations/{id}:
    delete:
      consumes:
      - '*/*'
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "204":
          description: No Content
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Delete Location
      tags:
      - locations
    get:
      consumes:
      - '*/*'
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Location'
        "500":
          description: ERROR
          schema:
            type: string
      summary: Get Location
      tags:
      - locations
schemes:
- http
swagger: "2.0"
